secrets:
  backend_ca:
    file: ${TLS_CA_PATH}
  nginx_client_crt:
    file: ${TLS_CLIENT_CERT_PATH}
  nginx_client_key:
    file: ${TLS_CLIENT_KEY_PATH}

services:
  frontend-test:
    image: phunpt01/react-frontend:latest
    container_name: frontend-test
    ports:
      - "8080:8080" # Simple HTTP port (no Cloudflare SSL)
    volumes:
      # --- Core Nginx Configuration Files (Common to both sites) ---
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/conf.d/upstream.conf:/etc/nginx/conf.d/upstream.conf:ro
      - ./etc/nginx/nginxconfig.io/proxy.conf:/etc/nginx/nginxconfig.io/proxy.conf:ro
      - ./etc/nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro

      # --- Site 1: admission.edu.vn Configuration ---
      - ./etc/nginx/sites-available/admission.staging.conf:/etc/nginx/sites-enabled/admission.staging.conf:ro

      # Avoid conflicts by mapping configuration snippets to unique destinations in the container
      - ./etc/nginx/nginxconfig.io/security.conf:/etc/nginx/nginxconfig.io/security.conf:ro
      - ./etc/nginx/nginxconfig.txt:/etc/nginx/nginxconfig.txt:ro

      # --- Site 2: galaxyfreedom.com Configuration ---
      - ./etc/nginx/sites-available/galaxyfreedom.staging.conf:/etc/nginx/sites-enabled/galaxyfreedom.staging.conf:ro

      # Avoid conflicts by mapping configuration snippets to unique destinations in the container
      - ./etc/nginx/nginxconfig.io/security.galaxyfreedom.com.conf:/etc/nginx/nginxconfig.io/security.galaxyfreedom.com.conf:ro
      - ./etc/nginx/nginxconfig.galaxyfreedom.com.txt:/etc/nginx/nginxconfig.galaxyfreedom.com.txt:ro
    secrets:
      - backend_ca
      - nginx_client_crt
      - nginx_client_key
    restart: unless-stopped
    networks:
      - frontend-network-test

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  frontend-network-test:
    external: true
    name: frontend-network-test
