name = "galaxy-freedom-worker"
main = "worker.js"
compatibility_date = "2024-12-16"

[vars]
AWS_ORIGIN = "https://3.82.69.9"

[[routes]]
pattern = "galaxyfreedom.com/*"
zone_name = "galaxyfreedom.com"

[[routes]]
pattern = "www.galaxyfreedom.com/*"
zone_name = "galaxyfreedom.com"

